services:
  - docker
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

stages:
  - lint
  - test
  - deploy

install:
  - make init
before_script:
  # - make python/dist
  - make build-test-lambda
script:
  - make pytest/k/unit pytest/k/integration
after_success:
  - codecov

jobs:
  include:
    - stage: lint
      python: 3.6
      services: []
      before_script: []
      script: make python/lint
      after_success: []
      deploy: []

    - stage: deploy
      if: tag =~ ^v
      python: 3.6
      services: []
      before_script: []
      script: make requirements.txt requirements-dev.txt
      after_success: []
      deploy:
        provider: pypi
        user: "__token__"
        password:
          secure: "bNcVuRs3yxH6hCx5LCvAPBZgww1kPTks+sEcWSOr9f0Nk4dCvxARr3covff/5WeXb5kvIWXtn4SKUbW+asNDFhjE1LlVb19XSKvUsEE/vhzYfHS2SzvuvoJ8bhu0J/EpFSNMveTuEEg267LudqstyUMcC0mHApewPZ/SdHfqkM+G/3wyRzCcHnMY1H1FkOkrCirMh0VklwCL+hZTpjFHYj0wweYIs61bZUUQtGDW6HYuQupERV0j/j8sZXveAvp2jN4HkPdM7/Hco92RS/GJqhJifa4h4WPsOseKHHYD25bzBp8UkYAldI/G1LPOZfJBBPMj/9Rwu6KCgZVbSquOo92oRUwZYcjsXT4/y0kgkbfSc4Kwl/T3B0M7STZ+j7GZOTcpmJman6AIjzVqIIR5b8DAd/kvIMG+eVCmLcS2fm3KbR5262rvKNWQ+XGVhm1z0OhshWPr6Pi2S/rhT7dGZ1eQacqfq1dk5WBXlJj34sT8MepRatDFZwSDwu9xsANB2Qcb328CI4vbKT2BoOCfw2yVdISDCn9mzbBS41kpTafMdrpl1fPmmVrJ4YvbD0YpQdwPB7bzD7Hc31Mj2q74PSOlDnBGpXI2LURdlO9d1K/Gbx8QZi0ZUot3sDUSmOjYgvpG/ORGbRBAbeiwTGmz+x/bKHD5s9W353yu0YZnYrE="
        distributions: 'sdist bdist_wheel'
        skip_existing: true
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
